import { describe, expect, it } from 'vitest';
import type { ForwardAllocationEvidence } from '../../../src/backend/reporting/forward-allocation/contracts.ts';
import { generateForwardAllocationRecommendations } from '../../../src/backend/reporting/forward-allocation/generate.ts';

const d = (iso: string): Date => new Date(`${iso}T00:00:00.000Z`);

function baseEvidence(): ForwardAllocationEvidence {
  return {
    window: {
      evidenceFrom: d('2026-06-29'),
      evidenceTo: d('2026-08-07'),
      planningStart: d('2026-08-10'),
      planningEnd: d('2026-10-04'),
    },
    modeSummary: {
      demandBackedCount: 2,
      inferredCount: 1,
    },
    facts: [],
    weeks: [],
    leaves: [],
    members: [
      {
        memberId: 'EMP-101',
        fullName: 'Member 101',
        department: 'Backend',
        roleTitle: 'Backend Developer',
        level: 'L3',
        lineManagerId: null,
        employmentStatus: 'Active',
        employmentType: 'FT',
        stdHoursWeek: 40,
        joinDate: d('2024-01-01'),
      },
      {
        memberId: 'EMP-102',
        fullName: 'Member 102',
        department: 'QA',
        roleTitle: 'QA Engineer',
        level: 'L3',
        lineManagerId: null,
        employmentStatus: 'Active',
        employmentType: 'FT',
        stdHoursWeek: 40,
        joinDate: d('2024-01-01'),
      },
      {
        memberId: 'EMP-103',
        fullName: 'Member 103',
        department: 'Design',
        roleTitle: 'Designer',
        level: 'L3',
        lineManagerId: null,
        employmentStatus: 'Active',
        employmentType: 'FT',
        stdHoursWeek: 40,
        joinDate: d('2024-01-01'),
      },
      {
        memberId: 'EMP-104',
        fullName: 'Member 104',
        department: 'Frontend',
        roleTitle: 'Frontend Developer',
        level: 'L3',
        lineManagerId: null,
        employmentStatus: 'Active',
        employmentType: 'FT',
        stdHoursWeek: 40,
        joinDate: d('2024-01-01'),
      },
    ],
    projects: [
      {
        project_id: 'PRJ-001',
        project_name: 'Alpha',
        account_id: null,
        project_type: 'delivery',
        project_domain: 'delivery',
        status: 'active',
        pm_id: null,
        start_date: d('2026-01-01'),
        end_date: d('2026-12-31'),
      },
      {
        project_id: 'PRJ-002',
        project_name: 'Beta',
        account_id: null,
        project_type: 'delivery',
        project_domain: 'delivery',
        status: 'active',
        pm_id: null,
        start_date: d('2026-01-01'),
        end_date: d('2026-12-31'),
      },
      {
        project_id: 'PRJ-003',
        project_name: 'Gamma',
        account_id: null,
        project_type: 'delivery',
        project_domain: 'delivery',
        status: 'active',
        pm_id: null,
        start_date: d('2026-01-01'),
        end_date: d('2026-12-31'),
      },
    ],
    allocations: [],
    demandWindows: [],
    demandGaps: [],
    riskByMember: new Map([
      [
        'EMP-101',
        {
          memberId: 'EMP-101',
          availableHours: 232,
          plannedHours: 180,
          loggedHours: 170,
          utilization: 0.73,
          effortConsumption: 0.94,
          overtimeRatio: 0,
          trainingHours: 0,
          benchHours: 24,
        },
      ],
      [
        'EMP-102',
        {
          memberId: 'EMP-102',
          availableHours: 232,
          plannedHours: 220,
          loggedHours: 220,
          utilization: 0.9483,
          effortConsumption: 1,
          overtimeRatio: 0.12,
          trainingHours: 0,
          benchHours: 0,
        },
      ],
      [
        'EMP-103',
        {
          memberId: 'EMP-103',
          availableHours: 232,
          plannedHours: 120,
          loggedHours: 110,
          utilization: 0.47,
          effortConsumption: 0.92,
          overtimeRatio: 0,
          trainingHours: 0,
          benchHours: 48,
        },
      ],
      [
        'EMP-104',
        {
          memberId: 'EMP-104',
          availableHours: 232,
          plannedHours: 232,
          loggedHours: 210,
          utilization: 0.9,
          effortConsumption: 0.9,
          overtimeRatio: 0,
          trainingHours: 0,
          benchHours: 0,
        },
      ],
    ]),
    skills: [
      {
        memberId: 'EMP-101',
        skillKey: 'nodejs',
        proficiencyLevel: 4,
        evidenceConfidence: 1,
        sourceVersion: 'v1',
      },
      {
        memberId: 'EMP-102',
        skillKey: 'qa',
        proficiencyLevel: 4,
        evidenceConfidence: 1,
        sourceVersion: 'v1',
      },
      {
        memberId: 'EMP-104',
        skillKey: 'react',
        proficiencyLevel: 4,
        evidenceConfidence: 1,
        sourceVersion: 'v1',
      },
    ],
    taskHistory: [
      {
        historyId: 'TASK-001',
        memberId: 'EMP-101',
        projectId: 'PRJ-001',
        allocationRole: 'BE',
        taskTitle: 'Backend work',
        taskSummary: null,
        skillTags: ['nodejs'],
        completedAt: d('2026-07-15'),
        evidenceConfidence: 1,
        embedding: null,
        embeddingModelId: null,
        embeddingSourceHash: null,
        sourceVersion: 'v1',
      },
      {
        historyId: 'TASK-002',
        memberId: 'EMP-102',
        projectId: 'PRJ-002',
        allocationRole: 'QA',
        taskTitle: 'QA work',
        taskSummary: null,
        skillTags: ['qa'],
        completedAt: d('2026-07-16'),
        evidenceConfidence: 1,
        embedding: null,
        embeddingModelId: null,
        embeddingSourceHash: null,
        sourceVersion: 'v1',
      },
      {
        historyId: 'TASK-003',
        memberId: 'EMP-104',
        projectId: 'PRJ-003',
        allocationRole: 'FE',
        taskTitle: 'Frontend work',
        taskSummary: null,
        skillTags: ['react'],
        completedAt: d('2026-07-17'),
        evidenceConfidence: 1,
        embedding: null,
        embeddingModelId: null,
        embeddingSourceHash: null,
        sourceVersion: 'v1',
      },
    ],
  };
}

describe('forward allocation matcher and ranking', () => {
  it('emits extend, reassign, fill-gap, and release-warning recommendations', () => {
    const evidence = baseEvidence();
    evidence.allocations = [
      {
        member_id: 'EMP-101',
        project_id: 'PRJ-001',
        role: 'BE',
        allocation_pct: 0.6,
        weekly_planned_hours: 24,
        start_date: d('2026-08-10'),
        end_date: d('2026-09-12'),
      },
      {
        member_id: 'EMP-102',
        project_id: 'PRJ-999',
        role: 'QA',
        allocation_pct: 1,
        weekly_planned_hours: 40,
        start_date: d('2026-08-10'),
        end_date: d('2026-08-29'),
      },
    ];
    evidence.demandGaps = [
      {
        demandId: 'DEM-001',
        projectId: 'PRJ-001',
        roleNeeded: 'BE',
        requiredSkills: ['nodejs'],
        demandStart: d('2026-08-10'),
        demandEnd: d('2026-09-12'),
        demandPct: 0.8,
        demandHoursPerWeek: 32,
        urgency: 'high',
        priorityScore: 0.9,
        confirmed: true,
        recommendationMode: 'demand_backed',
        demandSource: 'seeded_mock',
        note: null,
        evidenceFlags: [],
        supportingAllocationPct: 0.4,
        unresolvedDemandPct: 0.4,
        unresolvedDemandHoursPerWeek: 16,
        recommendationTypeHint: 'extend',
      },
      {
        demandId: 'DEM-002',
        projectId: 'PRJ-002',
        roleNeeded: 'QA',
        requiredSkills: ['qa'],
        demandStart: d('2026-09-01'),
        demandEnd: d('2026-10-04'),
        demandPct: 0.5,
        demandHoursPerWeek: 20,
        urgency: 'high',
        priorityScore: 0.8,
        confirmed: true,
        recommendationMode: 'demand_backed',
        demandSource: 'seeded_mock',
        note: null,
        evidenceFlags: [],
        supportingAllocationPct: 0,
        unresolvedDemandPct: 0.5,
        unresolvedDemandHoursPerWeek: 20,
        recommendationTypeHint: 'reassign',
      },
      {
        demandId: 'DEM-003',
        projectId: 'PRJ-003',
        roleNeeded: 'FE',
        requiredSkills: ['react'],
        demandStart: d('2026-08-10'),
        demandEnd: d('2026-09-20'),
        demandPct: 0.5,
        demandHoursPerWeek: 20,
        urgency: 'medium',
        priorityScore: 0.5,
        confirmed: false,
        recommendationMode: 'inferred',
        demandSource: 'seeded_mock',
        note: null,
        evidenceFlags: ['requires_demand_confirmation'],
        supportingAllocationPct: 0,
        unresolvedDemandPct: 0.5,
        unresolvedDemandHoursPerWeek: 20,
        recommendationTypeHint: 'fill_gap',
      },
    ];

    const rows = generateForwardAllocationRecommendations({ evidence, topN: 3 });

    expect(rows.some((row) => row.type === 'extend' && row.memberId === 'EMP-101')).toBe(true);
    expect(rows.some((row) => row.type === 'reassign' && row.memberId === 'EMP-102')).toBe(true);
    expect(rows.some((row) => row.type === 'fill_gap' && row.memberId === 'EMP-104')).toBe(true);
    expect(rows.some((row) => row.type === 'release_warning' && row.memberId === 'EMP-103')).toBe(
      true,
    );
  });

  it('keeps only the top-N ranked targets per availability window', () => {
    const evidence = baseEvidence();
    evidence.demandGaps = [
      {
        demandId: 'DEM-001',
        projectId: 'PRJ-001',
        roleNeeded: 'BE',
        requiredSkills: ['nodejs'],
        demandStart: d('2026-08-10'),
        demandEnd: d('2026-09-12'),
        demandPct: 0.4,
        demandHoursPerWeek: 16,
        urgency: 'high',
        priorityScore: 0.9,
        confirmed: true,
        recommendationMode: 'demand_backed',
        demandSource: 'seeded_mock',
        note: null,
        evidenceFlags: [],
        supportingAllocationPct: 0,
        unresolvedDemandPct: 0.4,
        unresolvedDemandHoursPerWeek: 16,
        recommendationTypeHint: 'fill_gap',
      },
      {
        demandId: 'DEM-002',
        projectId: 'PRJ-002',
        roleNeeded: 'BE',
        requiredSkills: ['nodejs'],
        demandStart: d('2026-08-10'),
        demandEnd: d('2026-09-20'),
        demandPct: 0.4,
        demandHoursPerWeek: 16,
        urgency: 'medium',
        priorityScore: 0.6,
        confirmed: true,
        recommendationMode: 'demand_backed',
        demandSource: 'seeded_mock',
        note: null,
        evidenceFlags: [],
        supportingAllocationPct: 0,
        unresolvedDemandPct: 0.4,
        unresolvedDemandHoursPerWeek: 16,
        recommendationTypeHint: 'fill_gap',
      },
      {
        demandId: 'DEM-003',
        projectId: 'PRJ-003',
        roleNeeded: 'BE',
        requiredSkills: ['nodejs'],
        demandStart: d('2026-08-10'),
        demandEnd: d('2026-09-20'),
        demandPct: 0.4,
        demandHoursPerWeek: 16,
        urgency: 'low',
        priorityScore: 0.2,
        confirmed: false,
        recommendationMode: 'inferred',
        demandSource: 'seeded_mock',
        note: null,
        evidenceFlags: ['requires_demand_confirmation'],
        supportingAllocationPct: 0,
        unresolvedDemandPct: 0.4,
        unresolvedDemandHoursPerWeek: 16,
        recommendationTypeHint: 'fill_gap',
      },
      {
        demandId: 'DEM-004',
        projectId: 'PRJ-004',
        roleNeeded: 'BE',
        requiredSkills: ['nodejs'],
        demandStart: d('2026-08-10'),
        demandEnd: d('2026-09-20'),
        demandPct: 0.4,
        demandHoursPerWeek: 16,
        urgency: 'low',
        priorityScore: 0.1,
        confirmed: false,
        recommendationMode: 'inferred',
        demandSource: 'seeded_mock',
        note: null,
        evidenceFlags: ['requires_demand_confirmation'],
        supportingAllocationPct: 0,
        unresolvedDemandPct: 0.4,
        unresolvedDemandHoursPerWeek: 16,
        recommendationTypeHint: 'fill_gap',
      },
    ];

    const rows = generateForwardAllocationRecommendations({ evidence, topN: 3 }).filter(
      (row) => row.memberId === 'EMP-101' && row.type !== 'release_warning',
    );

    expect(rows).toHaveLength(3);
    expect(rows.map((row) => row.targetProjectId)).toEqual(['PRJ-001', 'PRJ-002', 'PRJ-003']);
  });

  it('returns stable ranking for identical evidence', () => {
    const evidence = baseEvidence();
    evidence.demandGaps = [
      {
        demandId: 'DEM-010',
        projectId: 'PRJ-010',
        roleNeeded: 'BE',
        requiredSkills: ['nodejs'],
        demandStart: d('2026-08-10'),
        demandEnd: d('2026-09-12'),
        demandPct: 0.4,
        demandHoursPerWeek: 16,
        urgency: 'medium',
        priorityScore: 0.5,
        confirmed: true,
        recommendationMode: 'demand_backed',
        demandSource: 'seeded_mock',
        note: null,
        evidenceFlags: [],
        supportingAllocationPct: 0,
        unresolvedDemandPct: 0.4,
        unresolvedDemandHoursPerWeek: 16,
        recommendationTypeHint: 'fill_gap',
      },
      {
        demandId: 'DEM-011',
        projectId: 'PRJ-011',
        roleNeeded: 'BE',
        requiredSkills: ['nodejs'],
        demandStart: d('2026-08-10'),
        demandEnd: d('2026-09-12'),
        demandPct: 0.4,
        demandHoursPerWeek: 16,
        urgency: 'medium',
        priorityScore: 0.5,
        confirmed: true,
        recommendationMode: 'demand_backed',
        demandSource: 'seeded_mock',
        note: null,
        evidenceFlags: [],
        supportingAllocationPct: 0,
        unresolvedDemandPct: 0.4,
        unresolvedDemandHoursPerWeek: 16,
        recommendationTypeHint: 'fill_gap',
      },
    ];

    const first = generateForwardAllocationRecommendations({ evidence, topN: 3 })
      .filter((row) => row.memberId === 'EMP-101')
      .map((row) => row.recommendationId);
    const second = generateForwardAllocationRecommendations({ evidence, topN: 3 })
      .filter((row) => row.memberId === 'EMP-101')
      .map((row) => row.recommendationId);

    expect(first).toEqual(second);
    expect(first).toEqual(['EMP-101:DEM-010:fill_gap', 'EMP-101:DEM-011:fill_gap']);
  });
});
