// ── Canonical PMO Schema ─────────────────────────────────────────────────────
// Defines the target data model that all ingested workbooks must map into.
// Synonyms include Vietnamese terms for field matching.

export interface CanonicalField {
  name: string;
  label: string;
  dataType: 'string' | 'number' | 'date' | 'percentage' | 'boolean' | 'enum';
  required: boolean;
  synonyms: string[];
  valuePattern?: string;
  description: string;
}

export interface CanonicalTable {
  id: string;
  label: string;
  sheetNamePatterns: string[];
  fields: CanonicalField[];
  description: string;
}

export interface CanonicalSchema {
  version: string;
  tables: CanonicalTable[];
}

// ── Schema definition ────────────────────────────────────────────────────────

export const PMO_CANONICAL_SCHEMA: CanonicalSchema = {
  version: '1.1.0',
  tables: [
    {
      id: 'resource_allocation',
      label: 'Resource Allocation',
      description: 'Planned allocation of members to projects over date ranges (DS01).',
      sheetNamePatterns: ['resource.?alloc', 'ra', 'allocation', 'phân.?bổ.?nguồn.?lực', 'ds01'],
      fields: [
        {
          name: 'member_id',
          label: 'Member ID',
          dataType: 'string',
          required: true,
          synonyms: [
            'member_id',
            'employee_id',
            'emp_id',
            'staff_id',
            'user_id',
            'mã nhân viên',
            'mã nv',
            'ma nhan vien',
            'resource_id',
            'person_id',
            'worker_id',
          ],
          description: 'Member ID, FK to DS06.',
        },
        {
          name: 'project_id',
          label: 'Project ID',
          dataType: 'string',
          required: true,
          synonyms: [
            'project_id',
            'proj_id',
            'project_code',
            'project_no',
            'mã dự án',
            'ma du an',
            'mã da',
            'engagement_id',
            'job_id',
          ],
          description: 'Project ID, FK to DS05.',
        },
        {
          name: 'role',
          label: 'Role',
          dataType: 'enum',
          required: false,
          synonyms: ['role', 'allocation_role', 'role_code', 'vai trò', 'vai tro'],
          description: 'Allocation role code (e.g. BE, DE, ML, QA, DevOps).',
        },
        {
          name: 'allocation_pct',
          label: 'Allocation %',
          dataType: 'percentage',
          required: true,
          synonyms: [
            'allocation_pct',
            'allocation_percent',
            'allocation_%',
            'alloc_%',
            'alloc_pct',
            'tỷ lệ phân bổ',
            'ty le phan bo',
            '% phân bổ',
            'utilization',
            'fte',
            'capacity_%',
            'percent_allocated',
          ],
          valuePattern: '\\d+\\.?\\d*%?',
          description: 'Weekly allocation ratio (0.45 = 45%).',
        },
        {
          name: 'start_date',
          label: 'Start Date',
          dataType: 'date',
          required: true,
          synonyms: [
            'start_date',
            'from_date',
            'begin_date',
            'effective_from',
            'date_from',
            'ngày bắt đầu',
            'ngay bat dau',
            'từ ngày',
            'tu ngay',
          ],
          description: 'Allocation start date.',
        },
        {
          name: 'end_date',
          label: 'End Date',
          dataType: 'date',
          required: true,
          synonyms: [
            'end_date',
            'to_date',
            'finish_date',
            'effective_to',
            'date_to',
            'ngày kết thúc',
            'ngay ket thuc',
            'đến ngày',
            'den ngay',
          ],
          description: 'Allocation end date.',
        },
        {
          name: 'weekly_planned_hours',
          label: 'Weekly Planned Hours',
          dataType: 'number',
          required: false,
          synonyms: [
            'weekly_planned_hours',
            'planned_hours',
            'hours_planned',
            'budget_hours',
            'giờ kế hoạch',
            'gio ke hoach',
            'số giờ dự kiến',
          ],
          description: 'Planned hours per week (usually allocation_pct × std_hours_week).',
        },
      ],
    },
    {
      id: 'timesheet',
      label: 'Timesheet Log',
      description: 'Actual logged working hours per member per day (DS02).',
      sheetNamePatterns: [
        'timesheet',
        'time.?log',
        'time.?entry',
        'chấm.?công',
        'bảng.?công',
        'ds02',
      ],
      fields: [
        {
          name: 'member_id',
          label: 'Member ID',
          dataType: 'string',
          required: true,
          synonyms: [
            'member_id',
            'employee_id',
            'emp_id',
            'staff_id',
            'user_id',
            'mã nhân viên',
            'mã nv',
            'ma nhan vien',
            'resource_id',
            'person_id',
            'worker_id',
          ],
          description: 'Member ID, FK to DS06.',
        },
        {
          name: 'project_id',
          label: 'Project ID',
          dataType: 'string',
          required: false,
          synonyms: [
            'project_id',
            'proj_id',
            'project_code',
            'project_no',
            'mã dự án',
            'ma du an',
            'mã da',
            'engagement_id',
            'job_id',
          ],
          description: 'Project ID, can be null for internal/training logs.',
        },
        {
          name: 'work_date',
          label: 'Work Date',
          dataType: 'date',
          required: true,
          synonyms: [
            'work_date',
            'date',
            'log_date',
            'entry_date',
            'day',
            'ngày làm việc',
            'ngay lam viec',
            'ngày',
            'ngay',
          ],
          description: 'Work date.',
        },
        {
          name: 'logged_hours',
          label: 'Logged Hours',
          dataType: 'number',
          required: true,
          synonyms: [
            'logged_hours',
            'hours',
            'actual_hours',
            'worked_hours',
            'hrs',
            'giờ thực tế',
            'gio thuc te',
            'số giờ',
            'so gio',
            'giờ làm',
          ],
          valuePattern: '\\d+(\\.\\d+)?',
          description: 'Logged hours for the day.',
        },
        {
          name: 'log_category',
          label: 'Log Category',
          dataType: 'enum',
          required: false,
          synonyms: [
            'log_category',
            'category',
            'type',
            'work_type',
            'activity_type',
            'loại công việc',
            'loai cong viec',
            'phân loại',
            'phan loai',
          ],
          description: 'Log category (Project, Internal, Training, Admin).',
        },
        {
          name: 'task_ref',
          label: 'Task Reference',
          dataType: 'string',
          required: false,
          synonyms: [
            'task_ref',
            'task_reference',
            'task_id',
            'ticket',
            'jira_id',
            'mã task',
            'ma task',
            'mã công việc',
          ],
          description: 'Task reference ID, can be null.',
        },
      ],
    },
    {
      id: 'overbook_idle_config',
      label: 'Overbook/Idle Config',
      description: 'Rule thresholds for overbook, idle, and mismatch detection (DS03).',
      sheetNamePatterns: ['overbook', 'idle', 'config', 'rule', 'threshold', 'ds03'],
      fields: [
        {
          name: 'config_id',
          label: 'Config ID',
          dataType: 'string',
          required: true,
          synonyms: ['config_id', 'rule_id', 'id', 'mã cấu hình', 'ma cau hinh'],
          description: 'Rule configuration ID.',
        },
        {
          name: 'rule_name',
          label: 'Rule Name',
          dataType: 'string',
          required: true,
          synonyms: ['rule_name', 'name', 'ruleset', 'tên quy tắc', 'ten quy tac'],
          description: 'Rule set name.',
        },
        {
          name: 'overbook_threshold',
          label: 'Overbook Threshold',
          dataType: 'number',
          required: true,
          synonyms: [
            'overbook_threshold',
            'overbook_warn',
            'ob_threshold',
            'ngưỡng quá tải',
            'nguong qua tai',
          ],
          description: 'Overbook warning threshold (e.g. 1.10).',
        },
        {
          name: 'overbook_red_threshold',
          label: 'Overbook Red Threshold',
          dataType: 'number',
          required: false,
          synonyms: ['overbook_red_threshold', 'overbook_red', 'ob_red'],
          description: 'Red overbook threshold (e.g. 1.20).',
        },
        {
          name: 'idle_threshold',
          label: 'Idle Threshold',
          dataType: 'number',
          required: true,
          synonyms: [
            'idle_threshold',
            'idle_warn',
            'underutil_threshold',
            'ngưỡng nhàn rỗi',
            'nguong nhan roi',
          ],
          description: 'Idle threshold (e.g. below 0.75).',
        },
        {
          name: 'mismatch_pct_threshold',
          label: 'Mismatch % Threshold',
          dataType: 'number',
          required: false,
          synonyms: ['mismatch_pct_threshold', 'mismatch_threshold', 'mismatch_pct'],
          description: 'Logged vs planned mismatch threshold (e.g. 0.20).',
        },
        {
          name: 'ot_max_hours_per_week',
          label: 'OT Max Hours/Week',
          dataType: 'number',
          required: false,
          synonyms: ['ot_max_hours_per_week', 'ot_max', 'overtime_max', 'max_ot_hours'],
          description: 'Maximum weekly OT hours before review required.',
        },
        {
          name: 'effective_date',
          label: 'Effective Date',
          dataType: 'date',
          required: false,
          synonyms: [
            'effective_date',
            'effective_from',
            'valid_from',
            'ngày hiệu lực',
            'ngay hieu luc',
          ],
          description: 'Rule effective date.',
        },
      ],
    },
    {
      id: 'leave',
      label: 'Leave / Holiday Records',
      description: 'Leave, holiday, training, and approved OT compensation records (DS04).',
      sheetNamePatterns: ['leave', 'holiday', 'absence', 'nghỉ.?phép', 'nghi.?phep', 'ds04'],
      fields: [
        {
          name: 'record_id',
          label: 'Record ID',
          dataType: 'string',
          required: false,
          synonyms: ['record_id', 'leave_id', 'id', 'mã bản ghi', 'ma ban ghi'],
          description: 'Leave or holiday record ID.',
        },
        {
          name: 'member_id',
          label: 'Member ID',
          dataType: 'string',
          required: false,
          synonyms: [
            'member_id',
            'employee_id',
            'emp_id',
            'staff_id',
            'user_id',
            'mã nhân viên',
            'mã nv',
            'ma nhan vien',
            'resource_id',
            'person_id',
            'worker_id',
          ],
          description: 'Member ID, null for company-wide holidays.',
        },
        {
          name: 'leave_date',
          label: 'Leave Date',
          dataType: 'date',
          required: true,
          synonyms: [
            'leave_date',
            'date',
            'absence_date',
            'holiday_date',
            'ngày nghỉ',
            'ngay nghi',
            'ngày',
            'ngay',
          ],
          description: 'Leave, holiday, training, or OT comp date.',
        },
        {
          name: 'leave_type',
          label: 'Leave Type',
          dataType: 'enum',
          required: true,
          synonyms: [
            'leave_type',
            'type',
            'reason',
            'absence_type',
            'category',
            'loại nghỉ',
            'loai nghi',
            'lý do',
            'ly do',
          ],
          description: 'Record type (Annual Leave, Public Holiday, Training, Approved OT Comp).',
        },
        {
          name: 'approved',
          label: 'Approved',
          dataType: 'boolean',
          required: false,
          synonyms: ['approved', 'is_approved', 'approval', 'đã duyệt', 'da duyet', 'phê duyệt'],
          description: 'TRUE means the record is approved.',
        },
        {
          name: 'duration_days',
          label: 'Duration (Days)',
          dataType: 'number',
          required: false,
          synonyms: [
            'duration_days',
            'duration',
            'days',
            'num_days',
            'số ngày',
            'so ngay',
            'thời gian',
          ],
          description: 'Duration in days (e.g. 1.0 or 0.5).',
        },
        {
          name: 'note',
          label: 'Note',
          dataType: 'string',
          required: false,
          synonyms: [
            'note',
            'notes',
            'comment',
            'remark',
            'description',
            'ghi chú',
            'ghi chu',
            'mô tả',
            'mo ta',
          ],
          description: 'Additional note.',
        },
      ],
    },
    {
      id: 'project_master',
      label: 'Project Master',
      description: 'Project master data (DS05).',
      sheetNamePatterns: ['project', 'engagement', 'dự.?án', 'du.?an', 'ds05'],
      fields: [
        {
          name: 'project_id',
          label: 'Project ID',
          dataType: 'string',
          required: true,
          synonyms: [
            'project_id',
            'proj_id',
            'project_code',
            'project_no',
            'engagement_id',
            'mã dự án',
            'ma du an',
            'mã da',
            'job_id',
            'job_code',
          ],
          description: 'Project ID, logical primary key.',
        },
        {
          name: 'project_name',
          label: 'Project Name',
          dataType: 'string',
          required: true,
          synonyms: [
            'project_name',
            'name',
            'proj_name',
            'engagement_name',
            'title',
            'tên dự án',
            'ten du an',
            'tên da',
          ],
          description: 'Project name.',
        },
        {
          name: 'account_id',
          label: 'Account ID',
          dataType: 'string',
          required: false,
          synonyms: [
            'account_id',
            'client_id',
            'customer_id',
            'acct_id',
            'mã khách hàng',
            'ma khach hang',
          ],
          description: 'Account or client group ID.',
        },
        {
          name: 'project_type',
          label: 'Project Type',
          dataType: 'enum',
          required: false,
          synonyms: ['project_type', 'type', 'proj_type', 'category', 'loại dự án', 'loai du an'],
          description: 'Project type (Software, AI/ML Platform, Integration, Data).',
        },
        {
          name: 'status',
          label: 'Status',
          dataType: 'enum',
          required: false,
          synonyms: [
            'status',
            'project_status',
            'state',
            'phase',
            'trạng thái',
            'trang thai',
            'giai đoạn',
            'giai doan',
          ],
          description: 'Project status (Active, Completed, On Hold, Cancelled).',
        },
        {
          name: 'pm_id',
          label: 'PM ID',
          dataType: 'string',
          required: false,
          synonyms: [
            'pm_id',
            'project_manager',
            'pm',
            'manager_id',
            'owner',
            'người phụ trách',
            'nguoi phu trach',
            'quản lý dự án',
          ],
          description: 'Project manager ID, FK to DS06.',
        },
        {
          name: 'start_date',
          label: 'Start Date',
          dataType: 'date',
          required: false,
          synonyms: [
            'start_date',
            'from_date',
            'begin_date',
            'kick_off',
            'ngày bắt đầu',
            'ngay bat dau',
          ],
          description: 'Project start date.',
        },
        {
          name: 'end_date',
          label: 'End Date',
          dataType: 'date',
          required: false,
          synonyms: [
            'end_date',
            'to_date',
            'finish_date',
            'deadline',
            'due_date',
            'ngày kết thúc',
            'ngay ket thuc',
          ],
          description: 'Project end date.',
        },
      ],
    },
    {
      id: 'member_master',
      label: 'Member Master',
      description: 'Member master data (DS06).',
      sheetNamePatterns: [
        'member',
        'employee',
        'staff',
        'resource.?list',
        'nhân.?viên',
        'nhan.?vien',
        'ds06',
      ],
      fields: [
        {
          name: 'member_id',
          label: 'Member ID',
          dataType: 'string',
          required: true,
          synonyms: [
            'member_id',
            'employee_id',
            'emp_id',
            'staff_id',
            'user_id',
            'mã nhân viên',
            'mã nv',
            'ma nhan vien',
            'resource_id',
            'person_id',
            'worker_id',
          ],
          description: 'Member ID, logical primary key.',
        },
        {
          name: 'full_name',
          label: 'Full Name',
          dataType: 'string',
          required: true,
          synonyms: [
            'full_name',
            'name',
            'member_name',
            'employee_name',
            'staff_name',
            'tên nhân viên',
            'ten nhan vien',
            'họ tên',
            'ho ten',
            'họ và tên',
          ],
          description: 'Member full name.',
        },
        {
          name: 'department',
          label: 'Department',
          dataType: 'string',
          required: false,
          synonyms: [
            'department',
            'dept',
            'division',
            'team',
            'unit',
            'phòng ban',
            'phong ban',
            'bộ phận',
            'bo phan',
          ],
          description: 'Department (Backend, Data, AI/ML, PMO).',
        },
        {
          name: 'role_title',
          label: 'Role Title',
          dataType: 'string',
          required: false,
          synonyms: [
            'role_title',
            'role',
            'position',
            'job_title',
            'designation',
            'title',
            'vai trò',
            'vai tro',
            'chức danh',
            'chuc danh',
            'vị trí',
            'vi tri',
          ],
          description: 'Job title.',
        },
        {
          name: 'level',
          label: 'Level',
          dataType: 'string',
          required: false,
          synonyms: ['level', 'seniority', 'grade', 'band', 'cấp bậc', 'cap bac', 'cấp độ'],
          description: 'Seniority level (L2, L3, L4, L5, L6).',
        },
        {
          name: 'line_manager_id',
          label: 'Line Manager ID',
          dataType: 'string',
          required: false,
          synonyms: [
            'line_manager_id',
            'manager_id',
            'supervisor_id',
            'reports_to',
            'quản lý trực tiếp',
            'quan ly truc tiep',
          ],
          description: 'Line manager Member_ID (self-reference).',
        },
        {
          name: 'employment_status',
          label: 'Employment Status',
          dataType: 'enum',
          required: false,
          synonyms: [
            'employment_status',
            'emp_status',
            'status',
            'trạng thái',
            'trang thai',
            'tình trạng',
            'tinh trang',
          ],
          description: 'Employment status (Active, Probation, On Leave, Resigned).',
        },
        {
          name: 'employment',
          label: 'Employment Type',
          dataType: 'enum',
          required: false,
          synonyms: [
            'employment',
            'employment_type',
            'emp_type',
            'contract_type',
            'loại hợp đồng',
            'loai hop dong',
            'hình thức',
            'hinh thuc',
          ],
          description: 'Employment type (FT, PT).',
        },
        {
          name: 'std_hours_week',
          label: 'Standard Hours/Week',
          dataType: 'number',
          required: false,
          synonyms: [
            'std_hours_week',
            'standard_hours',
            'weekly_hours',
            'hours_per_week',
            'giờ chuẩn',
            'gio chuan',
            'số giờ/tuần',
          ],
          valuePattern: '\\d+(\\.\\d+)?',
          description: 'Standard weekly hours (40 for FT, 20 for PT).',
        },
        {
          name: 'join_date',
          label: 'Join Date',
          dataType: 'date',
          required: false,
          synonyms: [
            'join_date',
            'start_date',
            'hire_date',
            'onboard_date',
            'ngày vào',
            'ngay vao',
            'ngày gia nhập',
          ],
          description: 'Join date (used for onboarding edge cases).',
        },
      ],
    },
    {
      id: 'calendar_weeks',
      label: 'Calendar Weeks',
      description: 'Week calendar with working days and holidays (REF_Calendar_Weeks).',
      sheetNamePatterns: ['calendar', 'week', 'ref.?calendar', 'tuần', 'tuan'],
      fields: [
        {
          name: 'week_id',
          label: 'Week ID',
          dataType: 'string',
          required: true,
          synonyms: ['week_id', 'week_no', 'week_number', 'wk_id', 'mã tuần', 'ma tuan', 'tuần'],
          description: 'Week ID (e.g. W1, W2, W3).',
        },
        {
          name: 'week_start',
          label: 'Week Start',
          dataType: 'date',
          required: true,
          synonyms: [
            'week_start',
            'start_date',
            'from_date',
            'begin',
            'ngày bắt đầu tuần',
            'bat dau tuan',
          ],
          description: 'Week start date.',
        },
        {
          name: 'week_end',
          label: 'Week End',
          dataType: 'date',
          required: true,
          synonyms: [
            'week_end',
            'end_date',
            'to_date',
            'finish',
            'ngày kết thúc tuần',
            'ket thuc tuan',
          ],
          description: 'Week end date.',
        },
        {
          name: 'working_days',
          label: 'Working Days',
          dataType: 'number',
          required: true,
          synonyms: [
            'working_days',
            'work_days',
            'business_days',
            'num_days',
            'ngày làm việc',
            'ngay lam viec',
            'số ngày',
          ],
          description: 'Number of working days in the week.',
        },
        {
          name: 'holiday_hours_ft',
          label: 'Holiday Hours (FT)',
          dataType: 'number',
          required: false,
          synonyms: [
            'holiday_hours_ft',
            'holiday_hours',
            'holiday_reduction',
            'giờ nghỉ lễ',
            'gio nghi le',
          ],
          description: 'Holiday hours reducing available hours for FT members.',
        },
        {
          name: 'note',
          label: 'Note',
          dataType: 'string',
          required: false,
          synonyms: ['note', 'notes', 'comment', 'remark', 'ghi chú', 'ghi chu'],
          description: 'Notes (e.g. week with public holidays).',
        },
      ],
    },
    {
      id: 'kpi_norms',
      label: 'KPI Norms',
      description: 'KPI thresholds in Green/Yellow/Red bands (REF_KPI_Norms).',
      sheetNamePatterns: ['kpi', 'norm', 'ref.?kpi', 'threshold'],
      fields: [
        {
          name: 'norm_id',
          label: 'Norm ID',
          dataType: 'string',
          required: true,
          synonyms: ['norm_id', 'kpi_id', 'id', 'mã kpi', 'ma kpi'],
          description: 'KPI norm ID.',
        },
        {
          name: 'metric',
          label: 'Metric',
          dataType: 'string',
          required: true,
          synonyms: [
            'metric',
            'metric_name',
            'kpi_name',
            'indicator',
            'chỉ số',
            'chi so',
            'chỉ tiêu',
          ],
          description: 'Metric name (Busy Rate, Utilization Rate, Billable Rate).',
        },
        {
          name: 'formula',
          label: 'Formula',
          dataType: 'string',
          required: false,
          synonyms: ['formula', 'calculation', 'expression', 'công thức', 'cong thuc'],
          description: 'Formula used to compute the metric.',
        },
        {
          name: 'green',
          label: 'Green',
          dataType: 'string',
          required: false,
          synonyms: ['green', 'good', 'target'],
          description: 'Good threshold.',
        },
        {
          name: 'yellow',
          label: 'Yellow',
          dataType: 'string',
          required: false,
          synonyms: ['yellow', 'warning', 'caution'],
          description: 'Warning threshold.',
        },
        {
          name: 'red',
          label: 'Red',
          dataType: 'string',
          required: false,
          synonyms: ['red', 'critical', 'danger', 'alert'],
          description: 'Error/high-risk threshold.',
        },
        {
          name: 'used_for',
          label: 'Used For',
          dataType: 'string',
          required: false,
          synonyms: ['used_for', 'purpose', 'context', 'usage'],
          description: 'Purpose of KPI usage in this context.',
        },
      ],
    },
  ],
};

// ── Helper functions ─────────────────────────────────────────────────────────

export function getCanonicalTable(tableId: string): CanonicalTable | undefined {
  return PMO_CANONICAL_SCHEMA.tables.find((t) => t.id === tableId);
}

export function getRequiredFields(tableId: string): CanonicalField[] {
  const table = getCanonicalTable(tableId);
  if (!table) return [];
  return table.fields.filter((f) => f.required);
}

export interface SynonymIndex {
  /** Maps normalized synonym → { tableId, fieldName } */
  entries: Map<string, Array<{ tableId: string; fieldName: string }>>;
}

export function buildSynonymIndex(schema: CanonicalSchema = PMO_CANONICAL_SCHEMA): SynonymIndex {
  const entries = new Map<string, Array<{ tableId: string; fieldName: string }>>();

  for (const table of schema.tables) {
    for (const field of table.fields) {
      const allTerms = [field.name, ...field.synonyms];
      for (const term of allTerms) {
        const normalized = normalizeTerm(term);
        const existing = entries.get(normalized) ?? [];
        existing.push({ tableId: table.id, fieldName: field.name });
        entries.set(normalized, existing);
      }
    }
  }

  return { entries };
}

function normalizeTerm(term: string): string {
  return term
    .toLowerCase()
    .replace(/[_\-./]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}
