// ── PMO Domain Config (in-code constant) ────────────────────────────────────
// Source of truth for PMO ingestion domain configuration.
// The canonical equivalent JSON lives at config/ingestion-domains/pmo/domain.json.
// This TypeScript constant is kept for synchronous access by existing callers;
// the file-based registry loads the JSON version at runtime.

import { domainConfigToCanonicalSchema } from './canonical-compat.ts';
import type {
  DuplicatePolicy,
  IngestionDomainConfig,
  IngestionFieldConfig,
  IngestionReferenceRule,
  IngestionTableConfig,
} from './domain-config.ts';

// ── Reference resolution actions (shared across all PMO rules) ───────────────

const REFERENCE_RESOLUTION_ACTIONS: IngestionReferenceRule['resolutionActions'] = [
  'add_missing_master',
  'map_to_existing',
  'exclude_rows',
  'reject_run',
];

// ── Helper to build field with optional valuePattern ─────────────────────────

function field(
  f: Omit<IngestionFieldConfig, 'valuePattern'> & { valuePattern?: string },
): IngestionFieldConfig {
  const result: IngestionFieldConfig = {
    name: f.name,
    label: f.label,
    description: f.description,
    dataType: f.dataType,
    required: f.required,
    synonyms: f.synonyms,
  };
  if (f.valuePattern) result.valuePattern = f.valuePattern;
  return result;
}

// ── Tables ───────────────────────────────────────────────────────────────────

const RESOURCE_ALLOCATION: IngestionTableConfig = {
  id: 'resource_allocation',
  label: 'Resource Allocation',
  description: 'Planned allocation of members to projects over date ranges (DS01).',
  synonyms: ['resource.?alloc', 'ra', 'allocation', 'phân.?bổ.?nguồn.?lực', 'ds01'],
  naturalKey: ['member_id', 'project_id', 'start_date', 'end_date'],
  duplicatePolicy: 'block' as DuplicatePolicy,
  fields: [
    field({
      name: 'member_id',
      label: 'Member ID',
      description: 'Member ID, FK to DS06.',
      dataType: 'string',
      required: true,
      synonyms: [
        'member_id',
        'employee_id',
        'emp_id',
        'staff_id',
        'user_id',
        'mã nhân viên',
        'mã nv',
        'ma nhan vien',
        'resource_id',
        'person_id',
        'worker_id',
      ],
    }),
    field({
      name: 'project_id',
      label: 'Project ID',
      description: 'Project ID, FK to DS05.',
      dataType: 'string',
      required: true,
      synonyms: [
        'project_id',
        'proj_id',
        'project_code',
        'project_no',
        'mã dự án',
        'ma du an',
        'mã da',
        'engagement_id',
        'job_id',
      ],
    }),
    field({
      name: 'role',
      label: 'Role',
      description: 'Allocation role code (e.g. BE, DE, ML, QA, DevOps).',
      dataType: 'enum',
      required: false,
      synonyms: ['role', 'allocation_role', 'role_code', 'vai trò', 'vai tro'],
    }),
    field({
      name: 'allocation_pct',
      label: 'Allocation %',
      description: 'Weekly allocation ratio (0.45 = 45%).',
      dataType: 'percentage',
      required: true,
      synonyms: [
        'allocation_pct',
        'allocation_percent',
        'allocation_%',
        'alloc_%',
        'alloc_pct',
        'tỷ lệ phân bổ',
        'ty le phan bo',
        '% phân bổ',
        'utilization',
        'fte',
        'capacity_%',
        'percent_allocated',
      ],
      valuePattern: '\\d+\\.?\\d*%?',
    }),
    field({
      name: 'start_date',
      label: 'Start Date',
      description: 'Allocation start date.',
      dataType: 'date',
      required: true,
      synonyms: [
        'start_date',
        'from_date',
        'begin_date',
        'effective_from',
        'date_from',
        'ngày bắt đầu',
        'ngay bat dau',
        'từ ngày',
        'tu ngay',
      ],
    }),
    field({
      name: 'end_date',
      label: 'End Date',
      description: 'Allocation end date.',
      dataType: 'date',
      required: true,
      synonyms: [
        'end_date',
        'to_date',
        'finish_date',
        'effective_to',
        'date_to',
        'ngày kết thúc',
        'ngay ket thuc',
        'đến ngày',
        'den ngay',
      ],
    }),
    field({
      name: 'weekly_planned_hours',
      label: 'Weekly Planned Hours',
      description: 'Planned hours per week (usually allocation_pct × std_hours_week).',
      dataType: 'number',
      required: false,
      synonyms: [
        'weekly_planned_hours',
        'planned_hours',
        'hours_planned',
        'budget_hours',
        'giờ kế hoạch',
        'gio ke hoach',
        'số giờ dự kiến',
      ],
    }),
  ],
};

const TIMESHEET: IngestionTableConfig = {
  id: 'timesheet',
  label: 'Timesheet Log',
  description: 'Actual logged working hours per member per day (DS02).',
  synonyms: ['timesheet', 'time.?log', 'time.?entry', 'chấm.?công', 'bảng.?công', 'ds02'],
  naturalKey: ['member_id', 'work_date', 'project_id', 'log_category'],
  duplicatePolicy: 'skip' as DuplicatePolicy,
  fields: [
    field({
      name: 'member_id',
      label: 'Member ID',
      description: 'Member ID, FK to DS06.',
      dataType: 'string',
      required: true,
      synonyms: [
        'member_id',
        'employee_id',
        'emp_id',
        'staff_id',
        'user_id',
        'mã nhân viên',
        'mã nv',
        'ma nhan vien',
        'resource_id',
        'person_id',
        'worker_id',
      ],
    }),
    field({
      name: 'project_id',
      label: 'Project ID',
      description: 'Project ID, can be null for internal/training logs.',
      dataType: 'string',
      required: false,
      synonyms: [
        'project_id',
        'proj_id',
        'project_code',
        'project_no',
        'mã dự án',
        'ma du an',
        'mã da',
        'engagement_id',
        'job_id',
      ],
    }),
    field({
      name: 'work_date',
      label: 'Work Date',
      description: 'Work date.',
      dataType: 'date',
      required: true,
      synonyms: [
        'work_date',
        'date',
        'log_date',
        'entry_date',
        'day',
        'ngày làm việc',
        'ngay lam viec',
        'ngày',
        'ngay',
      ],
    }),
    field({
      name: 'logged_hours',
      label: 'Logged Hours',
      description: 'Logged hours for the day.',
      dataType: 'number',
      required: true,
      synonyms: [
        'logged_hours',
        'hours',
        'actual_hours',
        'worked_hours',
        'hrs',
        'giờ thực tế',
        'gio thuc te',
        'số giờ',
        'so gio',
        'giờ làm',
      ],
      valuePattern: '\\d+(\\.\\d+)?',
    }),
    field({
      name: 'log_category',
      label: 'Log Category',
      description: 'Log category (Project, Internal, Training, Admin).',
      dataType: 'enum',
      required: false,
      synonyms: [
        'log_category',
        'category',
        'type',
        'work_type',
        'activity_type',
        'loại công việc',
        'loai cong viec',
        'phân loại',
        'phan loai',
      ],
    }),
    field({
      name: 'task_ref',
      label: 'Task Reference',
      description: 'Task reference ID, can be null.',
      dataType: 'string',
      required: false,
      synonyms: [
        'task_ref',
        'task_reference',
        'task_id',
        'ticket',
        'jira_id',
        'mã task',
        'ma task',
        'mã công việc',
      ],
    }),
  ],
};

const OVERBOOK_IDLE_CONFIG: IngestionTableConfig = {
  id: 'overbook_idle_config',
  label: 'Overbook/Idle Config',
  description: 'Rule thresholds for overbook, idle, and mismatch detection (DS03).',
  synonyms: ['overbook', 'idle', 'config', 'rule', 'threshold', 'ds03'],
  naturalKey: ['config_id'],
  duplicatePolicy: 'block' as DuplicatePolicy,
  fields: [
    field({
      name: 'config_id',
      label: 'Config ID',
      description: 'Rule configuration ID.',
      dataType: 'string',
      required: true,
      synonyms: ['config_id', 'rule_id', 'id', 'mã cấu hình', 'ma cau hinh'],
    }),
    field({
      name: 'rule_name',
      label: 'Rule Name',
      description: 'Rule set name.',
      dataType: 'string',
      required: true,
      synonyms: ['rule_name', 'name', 'ruleset', 'tên quy tắc', 'ten quy tac'],
    }),
    field({
      name: 'overbook_threshold',
      label: 'Overbook Threshold',
      description: 'Overbook warning threshold (e.g. 1.10).',
      dataType: 'number',
      required: true,
      synonyms: [
        'overbook_threshold',
        'overbook_warn',
        'ob_threshold',
        'ngưỡng quá tải',
        'nguong qua tai',
      ],
    }),
    field({
      name: 'overbook_red_threshold',
      label: 'Overbook Red Threshold',
      description: 'Red overbook threshold (e.g. 1.20).',
      dataType: 'number',
      required: false,
      synonyms: ['overbook_red_threshold', 'overbook_red', 'ob_red'],
    }),
    field({
      name: 'idle_threshold',
      label: 'Idle Threshold',
      description: 'Idle threshold (e.g. below 0.75).',
      dataType: 'number',
      required: true,
      synonyms: [
        'idle_threshold',
        'idle_warn',
        'underutil_threshold',
        'ngưỡng nhàn rỗi',
        'nguong nhan roi',
      ],
    }),
    field({
      name: 'mismatch_pct_threshold',
      label: 'Mismatch % Threshold',
      description: 'Logged vs planned mismatch threshold (e.g. 0.20).',
      dataType: 'number',
      required: false,
      synonyms: ['mismatch_pct_threshold', 'mismatch_threshold', 'mismatch_pct'],
    }),
    field({
      name: 'ot_max_hours_per_week',
      label: 'OT Max Hours/Week',
      description: 'Maximum weekly OT hours before review required.',
      dataType: 'number',
      required: false,
      synonyms: ['ot_max_hours_per_week', 'ot_max', 'overtime_max', 'max_ot_hours'],
    }),
    field({
      name: 'effective_date',
      label: 'Effective Date',
      description: 'Rule effective date.',
      dataType: 'date',
      required: false,
      synonyms: [
        'effective_date',
        'effective_from',
        'valid_from',
        'ngày hiệu lực',
        'ngay hieu luc',
      ],
    }),
  ],
};

const LEAVE: IngestionTableConfig = {
  id: 'leave',
  label: 'Leave / Holiday Records',
  description: 'Leave, holiday, training, and approved OT compensation records (DS04).',
  synonyms: ['leave', 'holiday', 'absence', 'nghỉ.?phép', 'nghi.?phep', 'ds04'],
  naturalKey: ['member_id', 'leave_date', 'leave_type'],
  duplicatePolicy: 'block' as DuplicatePolicy,
  fields: [
    field({
      name: 'record_id',
      label: 'Record ID',
      description: 'Leave or holiday record ID.',
      dataType: 'string',
      required: false,
      synonyms: ['record_id', 'leave_id', 'id', 'mã bản ghi', 'ma ban ghi'],
    }),
    field({
      name: 'member_id',
      label: 'Member ID',
      description: 'Member ID, null for company-wide holidays.',
      dataType: 'string',
      required: false,
      synonyms: [
        'member_id',
        'employee_id',
        'emp_id',
        'staff_id',
        'user_id',
        'mã nhân viên',
        'mã nv',
        'ma nhan vien',
        'resource_id',
        'person_id',
        'worker_id',
      ],
    }),
    field({
      name: 'leave_date',
      label: 'Leave Date',
      description: 'Leave, holiday, training, or OT comp date.',
      dataType: 'date',
      required: true,
      synonyms: [
        'leave_date',
        'date',
        'absence_date',
        'holiday_date',
        'ngày nghỉ',
        'ngay nghi',
        'ngày',
        'ngay',
      ],
    }),
    field({
      name: 'leave_type',
      label: 'Leave Type',
      description: 'Record type (Annual Leave, Public Holiday, Training, Approved OT Comp).',
      dataType: 'enum',
      required: true,
      synonyms: [
        'leave_type',
        'type',
        'reason',
        'absence_type',
        'category',
        'loại nghỉ',
        'loai nghi',
        'lý do',
        'ly do',
      ],
    }),
    field({
      name: 'approved',
      label: 'Approved',
      description: 'TRUE means the record is approved.',
      dataType: 'boolean',
      required: false,
      synonyms: ['approved', 'is_approved', 'approval', 'đã duyệt', 'da duyet', 'phê duyệt'],
    }),
    field({
      name: 'duration_days',
      label: 'Duration (Days)',
      description: 'Duration in days (e.g. 1.0 or 0.5).',
      dataType: 'number',
      required: false,
      synonyms: [
        'duration_days',
        'duration',
        'days',
        'num_days',
        'số ngày',
        'so ngay',
        'thời gian',
      ],
    }),
    field({
      name: 'note',
      label: 'Note',
      description: 'Additional note.',
      dataType: 'string',
      required: false,
      synonyms: [
        'note',
        'notes',
        'comment',
        'remark',
        'description',
        'ghi chú',
        'ghi chu',
        'mô tả',
        'mo ta',
      ],
    }),
  ],
};

const PROJECT_MASTER: IngestionTableConfig = {
  id: 'project_master',
  label: 'Project Master',
  description: 'Project master data (DS05).',
  synonyms: ['project', 'engagement', 'dự.?án', 'du.?an', 'ds05'],
  naturalKey: ['project_id'],
  duplicatePolicy: 'block' as DuplicatePolicy,
  fields: [
    field({
      name: 'project_id',
      label: 'Project ID',
      description: 'Project ID, logical primary key.',
      dataType: 'string',
      required: true,
      synonyms: [
        'project_id',
        'proj_id',
        'project_code',
        'project_no',
        'engagement_id',
        'mã dự án',
        'ma du an',
        'mã da',
        'job_id',
        'job_code',
      ],
    }),
    field({
      name: 'project_name',
      label: 'Project Name',
      description: 'Project name.',
      dataType: 'string',
      required: true,
      synonyms: [
        'project_name',
        'name',
        'proj_name',
        'engagement_name',
        'title',
        'tên dự án',
        'ten du an',
        'tên da',
      ],
    }),
    field({
      name: 'account_id',
      label: 'Account ID',
      description: 'Account or client group ID.',
      dataType: 'string',
      required: false,
      synonyms: [
        'account_id',
        'client_id',
        'customer_id',
        'acct_id',
        'mã khách hàng',
        'ma khach hang',
      ],
    }),
    field({
      name: 'project_type',
      label: 'Project Type',
      description: 'Project type (Software, AI/ML Platform, Integration, Data).',
      dataType: 'enum',
      required: false,
      synonyms: ['project_type', 'type', 'proj_type', 'category', 'loại dự án', 'loai du an'],
    }),
    field({
      name: 'status',
      label: 'Status',
      description: 'Project status (Active, Completed, On Hold, Cancelled).',
      dataType: 'enum',
      required: false,
      synonyms: [
        'status',
        'project_status',
        'state',
        'phase',
        'trạng thái',
        'trang thai',
        'giai đoạn',
        'giai doan',
      ],
    }),
    field({
      name: 'pm_id',
      label: 'PM ID',
      description: 'Project manager ID, FK to DS06.',
      dataType: 'string',
      required: false,
      synonyms: [
        'pm_id',
        'project_manager',
        'pm',
        'manager_id',
        'owner',
        'người phụ trách',
        'nguoi phu trach',
        'quản lý dự án',
      ],
    }),
    field({
      name: 'start_date',
      label: 'Start Date',
      description: 'Project start date.',
      dataType: 'date',
      required: false,
      synonyms: [
        'start_date',
        'from_date',
        'begin_date',
        'kick_off',
        'ngày bắt đầu',
        'ngay bat dau',
      ],
    }),
    field({
      name: 'end_date',
      label: 'End Date',
      description: 'Project end date.',
      dataType: 'date',
      required: false,
      synonyms: [
        'end_date',
        'to_date',
        'finish_date',
        'deadline',
        'due_date',
        'ngày kết thúc',
        'ngay ket thuc',
      ],
    }),
  ],
};

const MEMBER_MASTER: IngestionTableConfig = {
  id: 'member_master',
  label: 'Member Master',
  description: 'Member master data (DS06).',
  synonyms: ['member', 'employee', 'staff', 'resource.?list', 'nhân.?viên', 'nhan.?vien', 'ds06'],
  naturalKey: ['member_id'],
  duplicatePolicy: 'block' as DuplicatePolicy,
  fields: [
    field({
      name: 'member_id',
      label: 'Member ID',
      description: 'Member ID, logical primary key.',
      dataType: 'string',
      required: true,
      synonyms: [
        'member_id',
        'employee_id',
        'emp_id',
        'staff_id',
        'user_id',
        'mã nhân viên',
        'mã nv',
        'ma nhan vien',
        'resource_id',
        'person_id',
        'worker_id',
      ],
    }),
    field({
      name: 'full_name',
      label: 'Full Name',
      description: 'Member full name.',
      dataType: 'string',
      required: true,
      synonyms: [
        'full_name',
        'name',
        'member_name',
        'employee_name',
        'staff_name',
        'tên nhân viên',
        'ten nhan vien',
        'họ tên',
        'ho ten',
        'họ và tên',
      ],
    }),
    field({
      name: 'department',
      label: 'Department',
      description: 'Department (Backend, Data, AI/ML, PMO).',
      dataType: 'string',
      required: false,
      synonyms: [
        'department',
        'dept',
        'division',
        'team',
        'unit',
        'phòng ban',
        'phong ban',
        'bộ phận',
        'bo phan',
      ],
    }),
    field({
      name: 'role_title',
      label: 'Role Title',
      description: 'Job title.',
      dataType: 'string',
      required: false,
      synonyms: [
        'role_title',
        'role',
        'position',
        'job_title',
        'designation',
        'title',
        'vai trò',
        'vai tro',
        'chức danh',
        'chuc danh',
        'vị trí',
        'vi tri',
      ],
    }),
    field({
      name: 'level',
      label: 'Level',
      description: 'Seniority level (L2, L3, L4, L5, L6).',
      dataType: 'string',
      required: false,
      synonyms: ['level', 'seniority', 'grade', 'band', 'cấp bậc', 'cap bac', 'cấp độ'],
    }),
    field({
      name: 'line_manager_id',
      label: 'Line Manager ID',
      description: 'Line manager Member_ID (self-reference).',
      dataType: 'string',
      required: false,
      synonyms: [
        'line_manager_id',
        'manager_id',
        'supervisor_id',
        'reports_to',
        'quản lý trực tiếp',
        'quan ly truc tiep',
      ],
    }),
    field({
      name: 'employment_status',
      label: 'Employment Status',
      description: 'Employment status (Active, Probation, On Leave, Resigned).',
      dataType: 'enum',
      required: false,
      synonyms: [
        'employment_status',
        'emp_status',
        'status',
        'trạng thái',
        'trang thai',
        'tình trạng',
        'tinh trang',
      ],
    }),
    field({
      name: 'employment',
      label: 'Employment Type',
      description: 'Employment type (FT, PT).',
      dataType: 'enum',
      required: false,
      synonyms: [
        'employment',
        'employment_type',
        'emp_type',
        'contract_type',
        'loại hợp đồng',
        'loai hop dong',
        'hình thức',
        'hinh thuc',
      ],
    }),
    field({
      name: 'std_hours_week',
      label: 'Standard Hours/Week',
      description: 'Standard weekly hours (40 for FT, 20 for PT).',
      dataType: 'number',
      required: false,
      synonyms: [
        'std_hours_week',
        'standard_hours',
        'weekly_hours',
        'hours_per_week',
        'giờ chuẩn',
        'gio chuan',
        'số giờ/tuần',
      ],
      valuePattern: '\\d+(\\.\\d+)?',
    }),
    field({
      name: 'join_date',
      label: 'Join Date',
      description: 'Join date (used for onboarding edge cases).',
      dataType: 'date',
      required: false,
      synonyms: [
        'join_date',
        'start_date',
        'hire_date',
        'onboard_date',
        'ngày vào',
        'ngay vao',
        'ngày gia nhập',
      ],
    }),
  ],
};

const CALENDAR_WEEKS: IngestionTableConfig = {
  id: 'calendar_weeks',
  label: 'Calendar Weeks',
  description: 'Week calendar with working days and holidays (REF_Calendar_Weeks).',
  synonyms: ['calendar', 'week', 'ref.?calendar', 'tuần', 'tuan'],
  naturalKey: ['week_id'],
  duplicatePolicy: 'block' as DuplicatePolicy,
  fields: [
    field({
      name: 'week_id',
      label: 'Week ID',
      description: 'Week ID (e.g. W1, W2, W3).',
      dataType: 'string',
      required: true,
      synonyms: ['week_id', 'week_no', 'week_number', 'wk_id', 'mã tuần', 'ma tuan', 'tuần'],
    }),
    field({
      name: 'week_start',
      label: 'Week Start',
      description: 'Week start date.',
      dataType: 'date',
      required: true,
      synonyms: [
        'week_start',
        'start_date',
        'from_date',
        'begin',
        'ngày bắt đầu tuần',
        'bat dau tuan',
      ],
    }),
    field({
      name: 'week_end',
      label: 'Week End',
      description: 'Week end date.',
      dataType: 'date',
      required: true,
      synonyms: [
        'week_end',
        'end_date',
        'to_date',
        'finish',
        'ngày kết thúc tuần',
        'ket thuc tuan',
      ],
    }),
    field({
      name: 'working_days',
      label: 'Working Days',
      description: 'Number of working days in the week.',
      dataType: 'number',
      required: true,
      synonyms: [
        'working_days',
        'work_days',
        'business_days',
        'num_days',
        'ngày làm việc',
        'ngay lam viec',
        'số ngày',
      ],
    }),
    field({
      name: 'holiday_hours_ft',
      label: 'Holiday Hours (FT)',
      description: 'Holiday hours reducing available hours for FT members.',
      dataType: 'number',
      required: false,
      synonyms: [
        'holiday_hours_ft',
        'holiday_hours',
        'holiday_reduction',
        'giờ nghỉ lễ',
        'gio nghi le',
      ],
    }),
    field({
      name: 'note',
      label: 'Note',
      description: 'Notes (e.g. week with public holidays).',
      dataType: 'string',
      required: false,
      synonyms: ['note', 'notes', 'comment', 'remark', 'ghi chú', 'ghi chu'],
    }),
  ],
};

const KPI_NORMS: IngestionTableConfig = {
  id: 'kpi_norms',
  label: 'KPI Norms',
  description: 'KPI thresholds in Green/Yellow/Red bands (REF_KPI_Norms).',
  synonyms: ['kpi', 'norm', 'ref.?kpi', 'threshold'],
  naturalKey: ['norm_id'],
  duplicatePolicy: 'block' as DuplicatePolicy,
  fields: [
    field({
      name: 'norm_id',
      label: 'Norm ID',
      description: 'KPI norm ID.',
      dataType: 'string',
      required: true,
      synonyms: ['norm_id', 'kpi_id', 'id', 'mã kpi', 'ma kpi'],
    }),
    field({
      name: 'metric',
      label: 'Metric',
      description: 'Metric name (Busy Rate, Utilization Rate, Billable Rate).',
      dataType: 'string',
      required: true,
      synonyms: ['metric', 'metric_name', 'kpi_name', 'indicator', 'chỉ số', 'chi so', 'chỉ tiêu'],
    }),
    field({
      name: 'formula',
      label: 'Formula',
      description: 'Formula used to compute the metric.',
      dataType: 'string',
      required: false,
      synonyms: ['formula', 'calculation', 'expression', 'công thức', 'cong thuc'],
    }),
    field({
      name: 'green',
      label: 'Green',
      description: 'Good threshold.',
      dataType: 'string',
      required: false,
      synonyms: ['green', 'good', 'target'],
    }),
    field({
      name: 'yellow',
      label: 'Yellow',
      description: 'Warning threshold.',
      dataType: 'string',
      required: false,
      synonyms: ['yellow', 'warning', 'caution'],
    }),
    field({
      name: 'red',
      label: 'Red',
      description: 'Error/high-risk threshold.',
      dataType: 'string',
      required: false,
      synonyms: ['red', 'critical', 'danger', 'alert'],
    }),
    field({
      name: 'used_for',
      label: 'Used For',
      description: 'Purpose of KPI usage in this context.',
      dataType: 'string',
      required: false,
      synonyms: ['used_for', 'purpose', 'context', 'usage'],
    }),
  ],
};

// ── PMO Domain Config ────────────────────────────────────────────────────────

export const PMO_DOMAIN_CONFIG: IngestionDomainConfig = {
  domainId: 'pmo',
  version: '1.1.0',
  label: 'PMO Resource Allocation and Timesheet',
  description:
    'PMO ingestion domain for Resource Allocation, Timesheet, master data, leave, calendar, and KPI norm workbooks.',
  tables: [
    RESOURCE_ALLOCATION,
    TIMESHEET,
    OVERBOOK_IDLE_CONFIG,
    LEAVE,
    PROJECT_MASTER,
    MEMBER_MASTER,
    CALENDAR_WEEKS,
    KPI_NORMS,
  ],
  referenceRules: [
    {
      sourceTable: 'resource_allocation',
      sourceField: 'member_id',
      targetTable: 'member_master',
      targetField: 'member_id',
      blocking: true,
      resolutionActions: REFERENCE_RESOLUTION_ACTIONS,
    },
    {
      sourceTable: 'timesheet',
      sourceField: 'member_id',
      targetTable: 'member_master',
      targetField: 'member_id',
      blocking: true,
      resolutionActions: REFERENCE_RESOLUTION_ACTIONS,
    },
    {
      sourceTable: 'leave',
      sourceField: 'member_id',
      targetTable: 'member_master',
      targetField: 'member_id',
      blocking: true,
      resolutionActions: REFERENCE_RESOLUTION_ACTIONS,
    },
    {
      sourceTable: 'resource_allocation',
      sourceField: 'project_id',
      targetTable: 'project_master',
      targetField: 'project_id',
      blocking: true,
      resolutionActions: REFERENCE_RESOLUTION_ACTIONS,
    },
    {
      sourceTable: 'timesheet',
      sourceField: 'project_id',
      targetTable: 'project_master',
      targetField: 'project_id',
      blocking: true,
      resolutionActions: REFERENCE_RESOLUTION_ACTIONS,
    },
  ],
  validationRules: [],
  publishPolicy: {
    requireApproval: true,
    allowDirectPublish: false,
    mode: 'staged',
  },
};

// ── Canonical schema compat (for scorers that still use CanonicalSchema) ─────

export const PMO_DOMAIN_CANONICAL_SCHEMA = domainConfigToCanonicalSchema(PMO_DOMAIN_CONFIG);
